repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(node_modules/|dist/|\.nuxt/)
      - id: end-of-file-fixer
        exclude: ^(node_modules/|dist/|\.nuxt/)
      - id: check-yaml
        exclude: ^(node_modules/|dist/|\.nuxt/)
      - id: check-added-large-files
        exclude: ^(node_modules/|dist/|\.nuxt/)
      - id: check-json
        exclude: ^(node_modules/|dist/|\.nuxt/)
      - id: check-toml
        exclude: ^(node_modules/|dist/|\.nuxt/)
      - id: debug-statements
        exclude: ^(node_modules/|dist/|\.nuxt/)

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3
        exclude: ^(node_modules/|dist/|\.nuxt/)

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: ^(node_modules/|dist/|\.nuxt/)

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^(node_modules/|dist/|\.nuxt/)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
        exclude: ^(node_modules/|dist/|\.nuxt/)

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        exclude: ^(node_modules/|dist/|\.nuxt/|tests/)
